engines:
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_paths:
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - docs/*
ratings:
  paths:
    - "**.go"
