language: go

go:
  - 1.8.x

env:
  CODECLIMATE_REPO_TOKEN: 9311a4b76692580fa889c7d2476a621b41f7ffb5554b8dabc5e818e572d0602c

before_script:
  - go get github.com/mattn/goveralls
  - go get github.com/AlekSi/gocoverutil

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev
  - env

go_import_path: github.com/hyeoncheon/goul

script:
  - go build -o goul -ldflags "-X main.buildNumber=`git rev-parse --short HEAD`" ./cmd/goul
  - ls -l goul
  - ./goul -v
  - ./test-gocover.sh
  - go test ./... -v
  - goveralls -v -service=travis-ci

